const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const names = Object.keys(pkg.dependencies || {}).concat(Object.keys(pkg.devDependencies || {})).sort();
const lines = [
  '# Third-party notices',
  '',
  'Direct dependencies of this repository. Generated by `npm run licenses`.',
  '',
];
for (const name of names) {
  const file = path.join(root, 'node_modules', name, 'package.json');
  if (!fs.existsSync(file)) {
    lines.push('- ' + name + ': not installed');
    continue;
  }
  const meta = JSON.parse(fs.readFileSync(file, 'utf8'));
  lines.push('- ' + name + '@' + (meta.version || '') + ' — ' + (meta.license || 'unknown'));
}
lines.push('');
fs.writeFileSync(path.join(root, 'THIRD_PARTY_NOTICES.md'), lines.join('\n'));
console.log('Wrote THIRD_PARTY_NOTICES.md');
